### ISSUE TITLE
Unable to login to Debian DC manager

### ISSUE THREAD

**Issue by samgaw58** [eesmer/DebianDC#1]
I did a fresh install of Debian DC using the ISO, I then opened the manager and setup a new domain. The server rebooted and whenever I try to login to the manager it won't accept the administrator password. Is there a default password that I've missed? Is there something else I should be doing to get logged in?

**Comment by eesmer** [comment]
Hello,
You can log in with the password of the administrator user account you assigned when setting up the domain.

If you cannot log in even though this password is correct;
Please check the domain and resolve from the terminal screen.
For example; ping domain_name

If the DebianDC machine cannot resolve the domain name, it means that the IP address has changed after domain installation or there is a problem with the DNS record.

**Comment by eesmer** [comment]
Hi,
For detailed logging, the lines in smb.conf sometimes stop the DNS service. I tested this several times.
I have removed the log settings for now. (additional setting)

The problem you are experiencing may be due to the DNS service stopping.
Important: The server should be listening on port 53 when you experience the problem.
If he doesn't listen, then this comment is correct.

You can test it.
